name: Compile Frimgur

on:
  workflow_dispatch:

jobs:
  compile-on-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - run: ./gradlew clean test fatJar
    - uses: actions/upload-artifact@v3
      with:
        name: frimgur-fat-jar
        path: build/libs/frimgur-jar-with-dependencies.jar

# vim: ts=2 sw=2 et
